"""Business rule codes for the media domain.

Centralizes rule_code constants used in BusinessRuleViolationException
to avoid typos and facilitate maintenance.
"""

from enum import StrEnum


class MediaRuleCodes(StrEnum):
    """Rule codes for media domain business rule violations."""

    EPISODE_SERIES_MISMATCH = "EPISODE_SERIES_MISMATCH"
    EPISODE_SEASON_MISMATCH = "EPISODE_SEASON_MISMATCH"
    SEASON_SERIES_MISMATCH = "SEASON_SERIES_MISMATCH"
    INTRO_EXCEEDS_DURATION = "INTRO_EXCEEDS_DURATION"
    INTRO_DETECTION_INVALID_TRANSITION = "INTRO_DETECTION_INVALID_TRANSITION"
    CREDITS_EXCEEDS_DURATION = "CREDITS_EXCEEDS_DURATION"
    MEDIA_CONFLICT_ALREADY_RESOLVED = "MEDIA_CONFLICT_ALREADY_RESOLVED"
    INVALID_RESOLUTION_ACTION = "INVALID_RESOLUTION_ACTION"
    MEDIA_CONFLICT_MERGE_INCOMPLETE = "MEDIA_CONFLICT_MERGE_INCOMPLETE"
    MEDIA_CONFLICT_WINNER_REQUIRED = "MEDIA_CONFLICT_WINNER_REQUIRED"
    MEDIA_CONFLICT_WINNER_NOT_IN_PAIR = "MEDIA_CONFLICT_WINNER_NOT_IN_PAIR"
    MEDIA_CONFLICT_WINNER_NOT_ALLOWED = "MEDIA_CONFLICT_WINNER_NOT_ALLOWED"


__all__ = ["MediaRuleCodes"]
