"""Collections DTOs."""

from src.modules.collections.application.dtos.custom_list_dtos import (
    AddItemToCustomListInput,
    CreateCustomListInput,
    CustomListItemOutput,
    CustomListItemsOutput,
    CustomListOutput,
    DeleteCustomListInput,
    FollowSharedListInput,
    GetCustomListItemsInput,
    GetSharedListPreviewInput,
    RemoveItemFromCustomListInput,
    RenameCustomListInput,
    ReorderCustomListItemsInput,
    RevokeCustomListShareInput,
    ShareCustomListInput,
    ShareCustomListOutput,
    SharedListMetaOutput,
    SharedListPreviewOutput,
    UnfollowCustomListInput,
)
from src.modules.collections.application.dtos.watchlist_dtos import (
    CheckWatchlistInput,
    GetWatchlistInput,
    ToggleWatchlistInput,
    ToggleWatchlistOutput,
    WatchlistItemOutput,
)

__all__ = [
    "AddItemToCustomListInput",
    "CheckWatchlistInput",
    "CreateCustomListInput",
    "CustomListItemOutput",
    "CustomListItemsOutput",
    "CustomListOutput",
    "DeleteCustomListInput",
    "FollowSharedListInput",
    "GetCustomListItemsInput",
    "GetSharedListPreviewInput",
    "GetWatchlistInput",
    "RemoveItemFromCustomListInput",
    "RenameCustomListInput",
    "ReorderCustomListItemsInput",
    "RevokeCustomListShareInput",
    "ShareCustomListInput",
    "ShareCustomListOutput",
    "SharedListMetaOutput",
    "SharedListPreviewOutput",
    "ToggleWatchlistInput",
    "ToggleWatchlistOutput",
    "UnfollowCustomListInput",
    "WatchlistItemOutput",
]
