"""Rule codes for Identity bounded context validation errors.

These codes are used for i18n translation of error messages.
"""


class IdentityRuleCodes:
    """Message codes for identity validation errors."""

    # Email validation
    EMAIL_EMPTY = "IDENTITY.EMAIL.EMPTY"
    EMAIL_INVALID_FORMAT = "IDENTITY.EMAIL.INVALID_FORMAT"
    EMAIL_TOO_LONG = "IDENTITY.EMAIL.TOO_LONG"

    # Profile name validation
    PROFILE_NAME_EMPTY = "IDENTITY.PROFILE.NAME.EMPTY"
    PROFILE_NAME_TOO_LONG = "IDENTITY.PROFILE.NAME.TOO_LONG"

    # Profile ownership / lifecycle
    PROFILE_OWNERSHIP_VIOLATION = "IDENTITY.PROFILE.OWNERSHIP_VIOLATION"
    PROFILE_NOT_FOUND = "IDENTITY.PROFILE.NOT_FOUND"
    CANNOT_DELETE_LAST_PROFILE = "IDENTITY.PROFILE.CANNOT_DELETE_LAST"

    # Session / authentication
    NO_ACTIVE_SESSION = "IDENTITY.SESSION.NONE"
    NO_ACTIVE_PROFILE = "IDENTITY.SESSION.NO_PROFILE_SELECTED"

    # Admin user surface
    USER_NOT_FOUND = "IDENTITY.USER.NOT_FOUND"
    USER_EMAIL_ALREADY_EXISTS = "IDENTITY.USER.EMAIL_ALREADY_EXISTS"
    USER_CANNOT_DELETE_SELF = "IDENTITY.USER.CANNOT_DELETE_SELF"
    USER_CANNOT_DEMOTE_LAST_ADMIN = "IDENTITY.USER.CANNOT_DEMOTE_LAST_ADMIN"

    # Account re-authentication
    ACCOUNT_PASSWORD_INVALID = "IDENTITY.ACCOUNT.PASSWORD_INVALID"

    # Parental controls (ADR-035)
    PARENTAL_PIN_INVALID_FORMAT = "IDENTITY.PARENTAL.PIN_INVALID_FORMAT"
    PARENTAL_PIN_REQUIRED = "IDENTITY.PARENTAL.PIN_REQUIRED"
    PARENTAL_PIN_INVALID = "IDENTITY.PARENTAL.PIN_INVALID"
    PARENTAL_PIN_LOCKED = "IDENTITY.PARENTAL.PIN_LOCKED"
    PARENTAL_PIN_NOT_CONFIGURED = "IDENTITY.PARENTAL.PIN_NOT_CONFIGURED"
    PARENTAL_PIN_IN_USE = "IDENTITY.PARENTAL.PIN_IN_USE"
