"""Media domain value objects (re-export for backwards compatibility)."""

from src.modules.media.domain.value_objects import (
    AudioTrack,
    Duration,
    EpisodeId,
    FilePath,
    Genre,
    HdrFormat,
    MediaFile,
    MediaId,
    MovieId,
    Resolution,
    SeasonId,
    SeriesId,
    SubtitleTrack,
    Title,
    VideoCodec,
    Year,
    parse_media_id,
)

__all__ = [
    "AudioTrack",
    "Duration",
    "EpisodeId",
    "FilePath",
    "Genre",
    "HdrFormat",
    "MediaFile",
    "MediaId",
    "MovieId",
    "Resolution",
    "SeasonId",
    "SeriesId",
    "SubtitleTrack",
    "Title",
    "VideoCodec",
    "Year",
    "parse_media_id",
]
