"""CreditsMarker value object — onset timestamp of a title's end credits."""

from datetime import datetime
from enum import StrEnum
from typing import Self

from pydantic import Field, model_validator

from src.building_blocks.domain import CompoundValueObject, utc_now


class CreditsMarkerSource(StrEnum):
    """How a :class:`CreditsMarker` was produced.

    Attributes:
        AUTO_DETECTED: Generated by the credits-detection job. Carries a
            ``confidence`` score and may be overwritten by a later
            detection pass with higher confidence.
        MANUAL: Set explicitly by a user via the API. Treated as
            authoritative — the auto-detection job must skip media whose
            marker is ``MANUAL``.
    """

    AUTO_DETECTED = "AUTO_DETECTED"
    MANUAL = "MANUAL"


class CreditsMarker(CompoundValueObject):
    """Onset of a title's end-credits segment.

    Unlike an intro (a bounded start/end window), credits run to the end
    of the file — so only the onset is stored. The player triggers
    "skip credits" / auto-next / mark-watched from ``start_seconds``.

    Attributes:
        start_seconds: Offset from the start of the title (seconds) where
            the credits begin. Must be ``>= 0``.
        source: Where the marker came from (auto-detection vs. manual edit).
        confidence: Detection confidence in ``[0.0, 1.0]``. Required when
            ``source == AUTO_DETECTED``; must be ``None`` when ``source ==
            MANUAL`` (a human-set marker has no algorithmic confidence).
        detected_at: When the marker was produced or last edited.

    Example:
        >>> CreditsMarker(
        ...     start_seconds=2551,
        ...     source=CreditsMarkerSource.AUTO_DETECTED,
        ...     confidence=0.86,
        ... )
    """

    start_seconds: int = Field(ge=0)
    source: CreditsMarkerSource
    confidence: float | None = Field(default=None, ge=0.0, le=1.0)
    detected_at: datetime = Field(default_factory=utc_now)

    @model_validator(mode="after")
    def _validate_invariants(self) -> Self:
        """Enforce the confidence/source cross-field invariant."""
        if self.source == CreditsMarkerSource.AUTO_DETECTED and self.confidence is None:
            raise ValueError("confidence is required when source is AUTO_DETECTED")

        if self.source == CreditsMarkerSource.MANUAL and self.confidence is not None:
            raise ValueError("confidence must be None when source is MANUAL")

        return self

    @property
    def is_manual(self) -> bool:
        """Return True if this marker was set manually by a user."""
        return self.source == CreditsMarkerSource.MANUAL


__all__ = ["CreditsMarker", "CreditsMarkerSource"]
