"""IntroMarker value object — start/end timestamps of an episode's intro segment."""

from datetime import datetime
from enum import StrEnum
from typing import Self

from pydantic import Field, model_validator

from src.building_blocks.domain import CompoundValueObject, utc_now


class IntroMarkerSource(StrEnum):
    """How an :class:`IntroMarker` was produced.

    Attributes:
        AUTO_DETECTED: Generated by the audio fingerprinting job. Carries
            a ``confidence`` score and may be overwritten by a later
            detection pass with higher confidence.
        MANUAL: Set explicitly by a user via the API. Treated as
            authoritative — the auto-detection job must skip episodes
            whose marker is ``MANUAL``.
    """

    AUTO_DETECTED = "AUTO_DETECTED"
    MANUAL = "MANUAL"


class IntroMarker(CompoundValueObject):
    """Start/end timestamps of an episode's intro segment.

    Attributes:
        start_seconds: Offset from the start of the episode (seconds).
            Must be ``>= 0``.
        end_seconds: Offset from the start of the episode (seconds).
            Must be strictly greater than ``start_seconds``.
        source: Where the marker came from (auto-detection vs. manual edit).
        confidence: Detection confidence in ``[0.0, 1.0]``. Required when
            ``source == AUTO_DETECTED``; must be ``None`` when ``source ==
            MANUAL`` (a human-set marker has no algorithmic confidence).
        detected_at: When the marker was produced or last edited.

    Example:
        >>> IntroMarker(
        ...     start_seconds=12,
        ...     end_seconds=98,
        ...     source=IntroMarkerSource.AUTO_DETECTED,
        ...     confidence=0.92,
        ... )
    """

    start_seconds: int = Field(ge=0)
    end_seconds: int = Field(ge=1)
    source: IntroMarkerSource
    confidence: float | None = Field(default=None, ge=0.0, le=1.0)
    detected_at: datetime = Field(default_factory=utc_now)

    @model_validator(mode="after")
    def _validate_invariants(self) -> Self:
        """Enforce cross-field invariants between range and source."""
        if self.end_seconds <= self.start_seconds:
            raise ValueError("end_seconds must be greater than start_seconds")

        if self.source == IntroMarkerSource.AUTO_DETECTED and self.confidence is None:
            raise ValueError("confidence is required when source is AUTO_DETECTED")

        if self.source == IntroMarkerSource.MANUAL and self.confidence is not None:
            raise ValueError("confidence must be None when source is MANUAL")

        return self

    @property
    def duration_seconds(self) -> int:
        """Return the length of the intro segment in seconds."""
        return self.end_seconds - self.start_seconds

    @property
    def is_manual(self) -> bool:
        """Return True if this marker was set manually by a user."""
        return self.source == IntroMarkerSource.MANUAL


__all__ = ["IntroMarker", "IntroMarkerSource"]
