"""Add the parental PIN hash to users.

Nullable, with no server default and no back-fill: NULL means no PIN is
configured (ADR-035), which is every account today. The CHECK refuses an
empty string so it can never stand in for "no PIN".

Written by hand on purpose, like ``ed6c3864ea50``. ``migrations/env.py``
turns on ``render_as_batch`` for SQLite, and the autogenerated batch
``add_column`` drops the CHECK. The batch ways of putting the named CHECK
back — ``batch_op.create_check_constraint`` or ``recreate="always"`` —
rebuild ``users`` by copy-and-rename. With foreign keys on (as ``env.py``
connects), dropping the old table fires ``profiles.user_id`` and
``access_tokens.user_id`` ``ON DELETE CASCADE``: every profile and every
session is deleted. A plain ``ALTER TABLE ... ADD COLUMN`` with the CHECK
inline keeps the table.

The CHECK is a column constraint so the native ``DROP COLUMN`` of the
downgrade is allowed; SQLite refuses to drop a column a table-level
CHECK names. ``tests/infrastructure/migrations/test_identity_parental_migrations.py``
runs this revision with foreign keys on over the previous schema.

Revision ID: 7737e1954c0c
Revises: ed6c3864ea50
Create Date: 2026-09-14 10:00:00.000000

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "7737e1954c0c"
down_revision: str | Sequence[str] | None = "ed6c3864ea50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the nullable, non-empty-checked parental_pin_hash column to users."""
    op.add_column(
        "users",
        sa.Column(
            "parental_pin_hash",
            sa.String(length=1024),
            sa.CheckConstraint(
                "parental_pin_hash IS NULL OR length(parental_pin_hash) > 0",
                name="ck_users_parental_pin_hash_not_empty",
            ),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Drop the parental_pin_hash column."""
    op.drop_column("users", "parental_pin_hash")
