"""Add the maturity limit to profiles.

Nullable, with no server default and no back-fill: NULL means
unrestricted (ADR-035), which is exactly what every existing profile
sees today, so the revision changes no one's catalog.

Written by hand on purpose. ``migrations/env.py`` turns on
``render_as_batch`` for SQLite, and the autogenerated batch
``add_column`` drops the CHECK. The batch ways of putting the named CHECK
back — ``batch_op.create_check_constraint`` or ``recreate="always"`` —
rebuild ``profiles`` by copy-and-rename, and with foreign keys on (as
``env.py`` connects) dropping the old table fires
``access_tokens.current_profile_id ON DELETE SET NULL`` and detaches
every session from its profile. A plain ``ALTER TABLE ... ADD COLUMN``
with the CHECK inline keeps the table, and SQLite validates that
constraint against the rows already there.

The CHECK is a column constraint so the native ``DROP COLUMN`` of the
downgrade is allowed; SQLite refuses to drop a column a table-level
CHECK names. ``tests/infrastructure/migrations/test_identity_parental_migrations.py``
runs this revision with foreign keys on over the previous schema.

Revision ID: ed6c3864ea50
Revises: a7e4c91d20b8
Create Date: 2026-09-13 21:30:00.000000

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "ed6c3864ea50"
down_revision: str | Sequence[str] | None = "a7e4c91d20b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the nullable, range-checked maturity_limit column to profiles."""
    op.add_column(
        "profiles",
        sa.Column(
            "maturity_limit",
            sa.Integer(),
            sa.CheckConstraint(
                "maturity_limit IS NULL OR maturity_limit BETWEEN 0 AND 21",
                name="ck_profiles_maturity_limit_range",
            ),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Drop the maturity_limit column."""
    op.drop_column("profiles", "maturity_limit")
