"""Initial schema.

Revision ID: 435d635e4b18
Revises:
Create Date: 2026-04-04 10:13:28.028649

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "435d635e4b18"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("original_title", sa.String(length=500), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("poster_path", sa.String(length=1000), nullable=True),
        sa.Column("backdrop_path", sa.String(length=1000), nullable=True),
        sa.Column("genres", sa.String(length=500), nullable=True),
        sa.Column("file_path", sa.String(length=2000), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("resolution", sa.String(length=20), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_movies_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_movies_external_id"), ["external_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_movies_file_path"), ["file_path"], unique=True)
        batch_op.create_index(batch_op.f("ix_movies_imdb_id"), ["imdb_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_movies_title"), ["title"], unique=False)
        batch_op.create_index(batch_op.f("ix_movies_tmdb_id"), ["tmdb_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_movies_year"), ["year"], unique=False)

    op.create_table(
        "series",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("original_title", sa.String(length=500), nullable=True),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("poster_path", sa.String(length=1000), nullable=True),
        sa.Column("backdrop_path", sa.String(length=1000), nullable=True),
        sa.Column("genres", sa.String(length=500), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_series_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_series_external_id"), ["external_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_series_imdb_id"), ["imdb_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_series_start_year"), ["start_year"], unique=False)
        batch_op.create_index(batch_op.f("ix_series_title"), ["title"], unique=False)
        batch_op.create_index(batch_op.f("ix_series_tmdb_id"), ["tmdb_id"], unique=False)

    op.create_table(
        "seasons",
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("series_external_id", sa.String(length=50), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("poster_path", sa.String(length=1000), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "season_number", name="uq_season_series_number"),
    )
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seasons_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_seasons_external_id"), ["external_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_seasons_series_external_id"), ["series_external_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_seasons_series_id"), ["series_id"], unique=False)

    op.create_table(
        "episodes",
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("series_external_id", sa.String(length=50), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=2000), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("resolution", sa.String(length=20), nullable=True),
        sa.Column("thumbnail_path", sa.String(length=1000), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "episode_number", name="uq_episode_season_number"),
    )
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_episodes_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_episodes_external_id"), ["external_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_episodes_file_path"), ["file_path"], unique=True)
        batch_op.create_index(batch_op.f("ix_episodes_season_id"), ["season_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_episodes_series_external_id"), ["series_external_id"], unique=False
        )

    op.create_table(
        "media_files",
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.Column("episode_id", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(length=2000), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("resolution_width", sa.Integer(), nullable=False),
        sa.Column("resolution_height", sa.Integer(), nullable=False),
        sa.Column("resolution_name", sa.String(length=20), nullable=False),
        sa.Column("video_codec", sa.String(length=20), nullable=True),
        sa.Column("video_bitrate", sa.Integer(), nullable=True),
        sa.Column("hdr_format", sa.String(length=30), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("audio_tracks_json", sa.Text(), nullable=True),
        sa.Column("subtitle_tracks_json", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(movie_id IS NOT NULL AND episode_id IS NULL) OR (movie_id IS NULL AND episode_id IS NOT NULL)",
            name="ck_media_file_single_owner",
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_media_files_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_files_episode_id"), ["episode_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_media_files_external_id"), ["external_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_media_files_file_path"), ["file_path"], unique=True)
        batch_op.create_index(batch_op.f("ix_media_files_movie_id"), ["movie_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_files_movie_id"))
        batch_op.drop_index(batch_op.f("ix_media_files_file_path"))
        batch_op.drop_index(batch_op.f("ix_media_files_external_id"))
        batch_op.drop_index(batch_op.f("ix_media_files_episode_id"))
        batch_op.drop_index(batch_op.f("ix_media_files_deleted_at"))

    op.drop_table("media_files")
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_episodes_series_external_id"))
        batch_op.drop_index(batch_op.f("ix_episodes_season_id"))
        batch_op.drop_index(batch_op.f("ix_episodes_file_path"))
        batch_op.drop_index(batch_op.f("ix_episodes_external_id"))
        batch_op.drop_index(batch_op.f("ix_episodes_deleted_at"))

    op.drop_table("episodes")
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seasons_series_id"))
        batch_op.drop_index(batch_op.f("ix_seasons_series_external_id"))
        batch_op.drop_index(batch_op.f("ix_seasons_external_id"))
        batch_op.drop_index(batch_op.f("ix_seasons_deleted_at"))

    op.drop_table("seasons")
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_series_tmdb_id"))
        batch_op.drop_index(batch_op.f("ix_series_title"))
        batch_op.drop_index(batch_op.f("ix_series_start_year"))
        batch_op.drop_index(batch_op.f("ix_series_imdb_id"))
        batch_op.drop_index(batch_op.f("ix_series_external_id"))
        batch_op.drop_index(batch_op.f("ix_series_deleted_at"))

    op.drop_table("series")
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movies_year"))
        batch_op.drop_index(batch_op.f("ix_movies_tmdb_id"))
        batch_op.drop_index(batch_op.f("ix_movies_title"))
        batch_op.drop_index(batch_op.f("ix_movies_imdb_id"))
        batch_op.drop_index(batch_op.f("ix_movies_file_path"))
        batch_op.drop_index(batch_op.f("ix_movies_external_id"))
        batch_op.drop_index(batch_op.f("ix_movies_deleted_at"))

    op.drop_table("movies")
    # ### end Alembic commands ###
